GET http://localhost:3000/grinders

###

POST http://localhost:3000/grinders
Content-Type: application/json

{
    "name": "Victoria Arduino Mythos 1"
}

###
POST http://localhost:3000/coffees
Content-Type: application/json

{
    "name": "Gail's House Blend"
}

###

GET http://localhost:3000/coffees

###

POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNiwidXNlcm5hbWUiOiJEYXZpZCIsImVtYWlsIjoiZGF2aWRAbXYzMi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR3eS5GNnhBeC5zUHM2dmQ1OURTU3BlM2lmNWhEQ3AuSEwzYUMzQ1FpUk81dVVJSTNqRUpRLiIsImNyZWF0ZWRBdCI6IjIwMjUtMDMtMTBUMTY6MzI6MTEuOTA4WiJ9LCJpYXQiOjE3NDE2MzE5NjUsImV4cCI6MTc0MjIzNjc2NX0.OtuJqm7owSPxZDQkBSbyta6WsyPFXKDFCU9FlCGdzgQ

{
     "title" : "davids recipe",
     "steps" : "brew coffee again",
     "brewMethod" : "aeropress",
     "grinder": "Victoria Arduino Mythos 1",
     "coffee": "Gail's House Blend"
}

###

GET http://localhost:3000/recipes



###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username" : "David12",
    "email" : "david12@mv32.com",
    "password" : "password123",
    "createdAt" : "2025-02-28T16:47:19.169Z"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "david@mv32.com",
    "password" : "password"
}


###
GET http://localhost:3000/recipes?user=Sam
