GET http://localhost:3000/grinders

###

POST http://localhost:3000/grinders
Content-Type: application/json

{
    "name": "Victoria Arduino Mythos 1"
}

###
POST http://localhost:3000/coffees
Content-Type: application/json

{
    "name": "Gail's House Blend"
}

###

GET http://localhost:3000/coffees

###

POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOYXZpZCIsImVtYWlsIjoiRGF2aWRAbXYzMi5jb20iLCJpYXQiOjE3NDE4NTk3ODksImV4cCI6MTc0MjQ2NDU4OX0.hAuiGiLK1XwhpaOTNFno7KDYyeHzR-Dzcg-vjPsSiwE

{
     "title" : "First recipe",
     "steps" : "brew coffee",
     "brewMethod" : "aeropress",
     "grinder": "Victoria Arduino Mythos 1",
     "coffee": "Red Brick"
}

###

GET http://localhost:3000/recipes



###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username" : "David12",
    "email" : "david12@mv32.com",
    "password" : "password123",
    "createdAt" : "2025-02-28T16:47:19.169Z"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "david@mv32.com",
    "password" : "password"
}


###
GET http://localhost:3000/recipes?grinder=Fellow%20Ode%20Gen2
